name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v1
        id: devkit-cache
        with:
          path: /opt/toolchains
          key: chilly-willy-devkit-3
      - name: Download The devkit archive
        if: steps.devkit-cache.outputs.cache-hit != 'true'
        run: | 
          curl -sL --fail \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/viciious/d32xr/releases/tags/devkit" \
          | jq -r ".assets | .[] | select(.name | test(\"chillys-sega-devkit-20190504-opt.tar.zst$\")) | .url" \
          | xargs curl -sL --fail -H "Accept: application/octet-stream" -o "chillys-sega-devkit-20190504-opt.tar.zst"
      - name: Unpack the devkit archive
        if: steps.devkit-cache.outputs.cache-hit != 'true'
        run: |
          ls -la ./chillys-sega-devkit-20190504-opt.tar.zst && \
          zstdcat ./chillys-sega-devkit-20190504-opt.tar.zst | sudo tar -C / -xa
      - uses: actions/checkout@v2
      - name: make debug MARS
        run: |
          dd if=/dev/zero bs=1K count=2324 of=doom32x.wad && \
          make -f Makefile.mars clean && make -f Makefile.mars debug
      - name: Print sizes
        run: nm --print-size --size-sort --radix=d D32XR.elf | egrep -Ei ' (B|D) ' | tail -n 20
      - name: make MARS
        run: |
          dd if=/dev/zero bs=1K count=2324 of=doom32x.wad && \
          make -f Makefile.mars clean && make -f Makefile.mars release
      - name: readelf -S
        run: |
          /opt/toolchains/sega/sh-elf/bin/sh-elf-readelf -S D32XR.elf
      - name: .bss plus .data size
        run: |
          /opt/toolchains/sega/sh-elf/bin/sh-elf-readelf -S D32XR.elf | \
          awk '{ if ($9 == "WA") { print 0"x"$7 } }' | \
          xargs printf "%d\n" | \
          awk '{s+=$1} END {print s}'
      - name: Archive ROM
        uses: actions/upload-artifact@v2
        with:
          name: 32X ROM File
          path: |
            D32XR.bin

